# Generated by Django 4.0.10 on 2024-06-19 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reimburse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimburse',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reimburse_approver_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reimburseline',
            name='attachment',
            field=models.FileField(default='', upload_to='reimburse_attachment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reimburse',
            name='state',
            field=models.CharField(choices=[('D', 'Draft'), ('S', 'Waiting Approval'), ('P', 'Paid'), ('R', 'Rejected')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='reimburse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimburse_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReimburseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=255)),
                ('reimburse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reimburse.reimburse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
